### ISSUE TITLE
setting up FUN (unclear)

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#116]
Would help if there is a bit of continuity between step 2) (compiling) and step 3 (setting up).

-  is this this step "git clone --depth 1 --branch master https://github.com/siemens/fluffi.git ./fluffigit necessary? As this was already done on step 2?
 - would also help if the checkout folder is the same as previous ... here it is used "fluffigit"

- touch /srv/fluffi/data/dnsmasq/dnsmasq.leases  should be done after the rsync command otherwise results in error "touch: cannot touch '/srv/fluffi/data/dnsmasq/dnsmasq.leases': No such file or directory
"
- Would be helpful if examples on how to change the default configuration are provided . E.g. using other ip then 10.66.0.1

**Comment by p0wer0xff** [comment]
You are right, there were several inconsistencies in the getting started guide that should be fixed by the linked PR. FLUFFI assumes that `10.66.0.1` is the master and that setting is used in several places. With the new documentation it should not be necessary to change the subnet, since FLUFFI is supposed to run in a separate network, and we [supply information](https://github.com/siemens/fluffi/commit/d492552c1db5fb3e96db9e740a770cb91aff6761#diff-90d2f5b321651d7e838fc1e3cf5f419bR242) on how to achieve internet connectivity through the master on a second network interface. Changing the fluffi subnet away from `10.66.0.0/23` is not supported by us, but can probably be done with little effort and a few `grep` and `sed` commands throughout the repository.
