### ISSUE TITLE
Setting up FUN (unclear doc) (2)

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#129]
In the setting up Fun there is the following section
"Replace the following dummy textfiles with their respective binaries. A link to obtain these is contained in the dummy files:

/srv/fluffi/data/smb/files/initial/updatesWS2008
/srv/fluffi/data/ftp/files/initial/windows/ansible"

However is not really clear what it should be done here ... what files should be replaced? 
![VirtualBox_ubuntu18 04_06_04_2020_10_59_24](https://user-images.githubusercontent.com/26308356/78535973-bd9b8400-77f5-11ea-9e87-50473bb00c2b.png)

**Comment by p0wer0xff** [comment]
All the actual files in these directories and their subdirectories are just placeholder textfiles that contain a link. These are mostly Microsoft proprietary binaries we cannot include in FLUFFI, so we link to where to get these files, you have to get them yourself, and replace the dummy files with the real ones by the same name. Since this is not clear from the documentation for you, could you please suggest a better wording, so we can prevent misunderstandings for future users?

**Comment by joyride9999** [comment]
I think a better wording would be : 
Download "package" from "link" and save it as "filename" in "path".
